#!/usr/bin/env bash
# This script configures domain zone so subdomain points to lb-01

# $1 = Domain
# $2 = Subdomain

display_subs ()
{
    domain=$1
    subdomain=$2
    dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline;
	printf "The subdomain %s is a %s record and points to %s\n",
	var, $4, $5}' var="$subdomain"
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$subdomain" ] ;
    then
	display_subs "$1" "$subdomain"
    fi
done
