#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.

if ! ( haproxy -v &>/dev/null ); then
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.6 -y
sudo apt update -y &&\
        sudo apt-get install haproxy=2.6.\* -y
fi

config=\
"
defaults
    mode http
    timeout client 30s
    timeout connect 15s
    timeout server 15s
    timeout http-request 15s

frontend viwe-teko-tech-frontend
    bind *:80
    default_backend viwe-teko-tech-backend

backend viwe-teko-tech-backend
    balance roundrobin
    server 482898-web-01 54.157.174.222:80 check
    server 482898-web-02 54.175.133.170:80 check
"

sudo cp /etc/haproxy/haproxy.cfg haproxy.cfg.backup

echo "$config" | sudo tee /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee /etc/default/haproxy

if [ "$(pgrep -c haproxy)" -eq 0 ]; then
    sudo service haproxy start
else
    sudo service haproxy restart
fi
