#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.4
apt-get -y update
apt-get install -y haproxy=2.4.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 482898-web-01 54.157.174.222:80 check
   server 482898-web-02 54.175.133.170:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
