#!/usr/bin/env bash
# This script displays contents of file '/etc/passwd'
# It only displays username, user id, and user home dir PATH

mine="/etc/passwd"

while IFS= read -r line
do
	echo "$line" | cut -d":" -f1,3,6
done < "$mine"
