#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 min,
# with hours displayed from 0 to 12, and minutes 1 to 59

hr=0

while [ $hr -le 12 ]
do
	echo "Hour: $hr"
	min=1
	while [ $min -le 59 ]
	do
		echo " $min"
		(( min++ ))
	done

	(( hr++ ))
done
